gt510wifi: remove libcamera_metadata
It has been removed in the checked-in list in the vendor repo, and
trying to build with it gives undefined reference to some camera
symbols (I guess these needs to be shimmed?).

Change-Id: I413ecb7c27baa86995a2e4aff979a24d8976bf9c